development:
  adapter: mysql2
  username: root
  password: password
  encoding: utf8
  database: journey_development
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: journey_production
