# Blurred background

CanvasImage = (e, t) ->
  @image = t
  @element = e
  @element.width = @image.width
  @element.height = @image.height
  n = navigator.userAgent.toLowerCase().indexOf('chrome') > -1
  r = navigator.appVersion.indexOf('Mac') > -1
  n and r and @element.width = Math.min(@element.width, 1680)
  @element.height = Math.min(@element.height, 1050)

  @context = @element.getContext('2d')
  @context.drawImage(@image, 0, 0)
  return

CanvasImage.prototype = blur: (e) ->
  @context.globalAlpha = .5
  t = -e
  while t <= e
    n = -e
    while n <= e
      @context.drawImage(@element, n, t)
      n >= 0 and t >= 0 and @context.drawImage(@element, -(n - 1), -(t - 1))
      n += 2
    t += 2
  @context.globalAlpha = 1
  return

$(->
  image = undefined
  canvasImage = undefined
  canvas = undefined
  $('.blur').each ->
    canvas = this
    image = new Image

    image.onload = ->
      canvasImage = new CanvasImage(canvas, this)
      canvasImage.blur(4)
      return

image.src = $(this).attr('src')
    return
  return
)
# Loader
loader = document.getElementById('loader')
border = document.getElementById('border')
α = 0
π = Math.PI
t = 180
(->
  α++
  α %= 360
  r = α * π / 180
  x = Math.sin(r) * 125
  y = Math.cos(r) * -125
  mid = if α > 180 then 1 else 0
  anim = 'M 0 0 v -125 A 125 125 1 ' + mid + ' 1 ' + x + ' ' + y + ' z'
  loader.setAttribute 'd', anim
  border.setAttribute 'd', anim
  setTimeout draw, t
  # Redraw
  return
)()

# ---
# generated by js2coffee 2.2.0